---

version: 2
updates:
  # 1) Обновление GitHub Actions (оставляем без изменений)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "automated"
      - "actions"
    groups:
      actions-minor-patch:
        update-types: ["minor", "patch"]
      actions-major:
        update-types: ["major"]

  # 2) Настройка под Maven (изменено с gradle на maven)
  - package-ecosystem: "maven"
    directory: "/" # Корень проекта, где лежит ваш pom.xml
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "automated"
      - "maven"
    groups:
      # Группировка всех минорных и патч-обновлений библиотек в один PR
      maven-deps-minor-patch:
        patterns:
          - "*"
        update-types: ["minor", "patch"]